/* Throwaway golden-vector generator. Links omega dual/0a-records rx_dual.c + sha256.c.
 * Prints "name hex" lines; "# " lines are comments. Status lines print the C
 * checker's RxDualStatus for hostile inputs so the Rust port can be compared. */
#include "rx_dual.h"
#include "sha256.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

static void hex(const char *name, const uint8_t *b, size_t n) {
    printf("%s ", name);
    for (size_t i = 0; i < n; i++) printf("%02x", b[i]);
    printf("\n");
}
static RxDualDigest tag(const char *s) {
    RxDualDigest d; sha256_hash((const uint8_t *)s, strlen(s), d.b); return d;
}
static RxDualDigest zero(void) { RxDualDigest d; memset(&d, 0, sizeof d); return d; }

static RxDualConstraintState cs(uint32_t id, RxDualUnit unit, RxDualClass cls, double lambda,
                                RxDualLambdaState st, int calibrated, uint64_t gen, uint64_t tick) {
    RxDualConstraintState s; memset(&s, 0, sizeof s);
    s.resource_id = id; s.unit = unit; s.cls = cls;
    s.budget = 4096.0;
    s.budget_contract = tag("budget-contract");
    s.observation_ref = tag("observation");
    s.estimate_ref = tag("estimate");
    s.estimate_kind = RX_DUAL_EST_MEASURED;
    s.estimate = 3900.5; s.uncertainty = 12.25;
    s.calibration_ref = calibrated ? tag("est3-calibration-receipt") : zero();
    s.lambda = lambda; s.lambda_state = st;
    s.controller_id = tag("controller");
    s.generation = gen; s.tick = tick;
    s.evidence_root = tag("evidence-root");
    s.parent = tick ? tag("parent-state") : zero();
    return s;
}

#define ENC(name, encfn, digfn, dom, obj) do { \
    uint8_t buf[RX_DUAL_ENCODED_MAX]; size_t len = 0; RxDualDigest d; \
    RxDualStatus st = encfn(&(obj), buf, sizeof buf, &len); \
    if (st != RX_DUAL_OK) { printf("# ENCODE FAIL %s st=%d\n", name, (int)st); return 1; } \
    st = digfn(&(obj), &d); if (st != RX_DUAL_OK) { printf("# DIGEST FAIL %s\n", name); return 1; } \
    hex(name, buf, len); hex(name ".digest", d.b, 32); } while (0)

int main(void) {
    printf("# generated by gen.c against omega dual/0a-records src/dual/rx_dual.c + src/sha256.c\n");
    printf("# tag(x) = SHA-256(x) used as placeholder digests\n");

    RxDualResource res; memset(&res, 0, sizeof res);
    res.resource_id = 5; res.unit = RX_DUAL_UNIT_KV_BLOCKS; res.scale = 1024.0; res.contract = tag("contract-kv");
    ENC("resource_kv", rx_dual_encode_resource, rx_dual_digest_resource, RX_DUAL_DOMAIN_RESOURCE, res);

    RxDualConstraintState c_ns  = cs(2, RX_DUAL_UNIT_NS, RX_DUAL_CLASS_SOFT, 0.42, RX_DUAL_LAMBDA_FRESH, 1, 7, 3);
    RxDualConstraintState c_kv  = cs(5, RX_DUAL_UNIT_KV_BLOCKS, RX_DUAL_CLASS_SOFT, 0.42, RX_DUAL_LAMBDA_FRESH, 1, 7, 3);
    RxDualConstraintState c_cap = cs(9, RX_DUAL_UNIT_BYTES, RX_DUAL_CLASS_CAPACITY, 0.1, RX_DUAL_LAMBDA_FRESH, 1, 7, 0);
    RxDualConstraintState c_st  = cs(5, RX_DUAL_UNIT_KV_BLOCKS, RX_DUAL_CLASS_SOFT, 0.42, RX_DUAL_LAMBDA_STALE, 0, 7, 4);
    RxDualConstraintState c_unc = cs(7, RX_DUAL_UNIT_PJ, RX_DUAL_CLASS_SOFT, 3.0, RX_DUAL_LAMBDA_UNCALIBRATED, 0, 7, 0);
    RxDualConstraintState c_fro = cs(11, RX_DUAL_UNIT_WATT, RX_DUAL_CLASS_SOFT, 0.7, RX_DUAL_LAMBDA_FROZEN, 1, 7, 2);
    /* negative zero lambda: must encode as +0.0 */
    RxDualConstraintState c_nz  = cs(3, RX_DUAL_UNIT_NS, RX_DUAL_CLASS_SOFT, -0.0, RX_DUAL_LAMBDA_FRESH, 1, 7, 0);

    ENC("constraint_fresh_soft_ns", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_ns);
    ENC("constraint_fresh_soft_kv", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_kv);
    ENC("constraint_fresh_capacity", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_cap);
    ENC("constraint_stale", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_st);
    ENC("constraint_uncalibrated", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_unc);
    ENC("constraint_frozen", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_fro);
    ENC("constraint_negzero_lambda", rx_dual_encode_constraint, rx_dual_digest_constraint, RX_DUAL_DOMAIN_CONSTRAINT, c_nz);

    RxDualController ctl; memset(&ctl, 0, sizeof ctl);
    ctl.eta = 0.05; ctl.rho = 0.01; ctl.k_sigma = 2.0; ctl.max_age = 16; ctl.cadence = 1; ctl.n = 3;
    ctl.resource_id[0] = 2; ctl.lambda_max[0] = 10.0;
    ctl.resource_id[1] = 5; ctl.lambda_max[1] = 10.0;
    ctl.resource_id[2] = 9; ctl.lambda_max[2] = 1.0;
    ENC("controller", rx_dual_encode_controller, rx_dual_digest_controller, RX_DUAL_DOMAIN_CONTROLLER, ctl);

    RxDualDigest ctx = tag("decision-context");
    RxDualPriceVector pv;
    const RxDualConstraintState *a[3] = { &c_ns, &c_kv, &c_cap };
    if (rx_dual_price_vector_build(a, 3, &ctx, &pv) != RX_DUAL_OK) { printf("# PV_A build fail\n"); return 1; }
    ENC("pricevec_a", rx_dual_encode_price_vector, rx_dual_digest_price_vector, RX_DUAL_DOMAIN_PRICE_VECTOR, pv);
    const RxDualConstraintState *b[2] = { &c_st, &c_unc };
    if (rx_dual_price_vector_build(b, 2, &ctx, &pv) != RX_DUAL_OK) { printf("# PV_B build fail\n"); return 1; }
    ENC("pricevec_b", rx_dual_encode_price_vector, rx_dual_digest_price_vector, RX_DUAL_DOMAIN_PRICE_VECTOR, pv);
    const RxDualConstraintState *c[2] = { &c_unc, &c_cap };
    if (rx_dual_price_vector_build(c, 2, &ctx, &pv) != RX_DUAL_OK) { printf("# PV_C build fail\n"); return 1; }
    ENC("pricevec_c", rx_dual_encode_price_vector, rx_dual_digest_price_vector, RX_DUAL_DOMAIN_PRICE_VECTOR, pv);
    const RxDualConstraintState *d[2] = { &c_fro, &c_unc };
    /* unordered on purpose: must be refused by the builder */
    printf("# builder unordered (11,7) status %d\n", (int)rx_dual_price_vector_build(d, 2, &ctx, &pv));

    /* ---- hostile cases: C checker status for mutated encodings ---- */
    uint8_t buf[RX_DUAL_ENCODED_MAX]; size_t len = 0; RxDualConstraintState out;
    rx_dual_encode_constraint(&c_kv, buf, sizeof buf, &len);
    printf("# constraint encoded length %zu\n", len);
    uint8_t m[RX_DUAL_ENCODED_MAX];
#define MUT(name, body) do { memcpy(m, buf, len); size_t ml = len; body; \
    printf("status %s %d\n", name, (int)rx_dual_decode_constraint(m, ml, &out)); } while (0)
    MUT("wrong_kind", m[0] = 4);
    MUT("wrong_version", m[1] = 2);
    MUT("truncated", ml = len - 1);
    MUT("trailing", m[len] = 0; ml = len + 1);
    MUT("class_invariant", m[10] = 1);
    MUT("class_undeclared", m[10] = 0);
    MUT("unit_none", m[6] = 0);
    MUT("unit_unknown", m[6] = 16);
    /* lambda at offset 2+4+4+4+8+32+32+32+4+8+8+32 = 170 */
    MUT("lambda_negative", m[177] |= 0x80);
    MUT("lambda_nan", { double nan = NAN; memcpy(m + 170, &nan, 8); });
    MUT("lambda_inf", { double inf = INFINITY; memcpy(m + 170, &inf, 8); });
    /* uncertainty at offset 2+4+4+4+8+32+32+32+4+8 = 130 */
    MUT("uncertainty_negative", m[137] |= 0x80);
    /* calibration_ref at 138..169: zero it while FRESH */
    MUT("fresh_without_calibration", memset(m + 138, 0, 32));
    /* evidence_root at 170+8+4+32+8+8 = 230..261 */
    MUT("evidence_root_zero", memset(m + 230, 0, 32));
    /* parent at 262..293: zero while tick=3 */
    MUT("parent_zero_with_tick", memset(m + 262, 0, 32));
    /* tick at 222..229: zero while parent nonzero */
    MUT("tick_zero_with_parent", memset(m + 222, 0, 8));
    /* estimate_kind at 118: 0 and 4 */
    MUT("estimate_kind_zero", m[118] = 0);
    MUT("estimate_kind_four", m[118] = 4);
    /* lambda_state at 178: 0 and 6 */
    MUT("lambda_state_zero", m[178] = 0);
    MUT("lambda_state_six", m[178] = 6);
    /* observation_ref at 54..85 zero while MEASURED */
    MUT("measured_without_observation", memset(m + 54, 0, 32));
    /* budget_contract at 22..53 */
    MUT("budget_contract_zero", memset(m + 22, 0, 32));

    /* price vector hostile */
    RxDualPriceVector pvo; size_t plen = 0;
    const RxDualConstraintState *aa[3] = { &c_ns, &c_kv, &c_cap };
    rx_dual_price_vector_build(aa, 3, &ctx, &pv);
    rx_dual_encode_price_vector(&pv, buf, sizeof buf, &plen);
    printf("# pricevec_a encoded length %zu\n", plen);
#define PMUT(name, body) do { memcpy(m, buf, plen); size_t ml = plen; body; \
    printf("status %s %d\n", name, (int)rx_dual_decode_price_vector(m, ml, &pvo)); } while (0)
    PMUT("pv_wrong_kind", m[0] = 2);
    PMUT("pv_wrong_version", m[1] = 0);
    PMUT("pv_truncated", ml = plen - 5);
    PMUT("pv_trailing", m[plen] = 7; ml = plen + 1);
    /* ids at 2+8+32+4 = 46: (46,id0)(50..81 dig)(82,id1)(86..117)(118,id2) */
    PMUT("pv_unordered_ids", { m[46] = 5; m[82] = 2; });
    PMUT("pv_duplicate_ids", m[82] = 2);
    PMUT("pv_zero_state_digest", memset(m + 50, 0, 32));
    PMUT("pv_zero_context", memset(m + 10, 0, 32));
    PMUT("pv_n_zero", { m[42] = 0; ml = 46; });
    PMUT("pv_n_too_large", m[42] = 33);
    return 0;
}
